# TensorFlow 입문

## TensorFlow 설치와 동작 확인하기

In [1]:
import tensorflow as tf
sess = tf.Session()
hello = tf.constant('Hello')
print(sess.run(hello))

b'Hello'


## TensorFlow 데이터 플로 그래프

### 덧셈하는 데이터 플로 그래프

In [2]:
# TensorFlow 읽어들이기
import tensorflow as tf

# 상수 정의하기
a = tf.constant(100)
b = tf.constant(30)

# 연산 정의하기
add_op = a + b

# 세션 시작하기
sess = tf.Session()
res = sess.run(add_op)  # 식 평가하기
print(res)

130


### 곱셈하는 데이터 플로 그래프

In [3]:
# TensorFlow 읽어들이기
import tensorflow as tf

# 상수 정의하기
a = tf.constant(10)
b = tf.constant(20)
c = tf.constant(30)

# 연산 정의하기
mul_op = (a + b) * c

# 세션 시작하기
sess = tf.Session()
res = sess.run(mul_op)  # 식 평가하기
print(res)

900


### 데이터 플로 그래프를 그림으로 확인하기

In [4]:
# TensorFlow 읽어들이기
import tensorflow as tf

# 상수 정의하기
a = tf.constant(10, name='10')
b = tf.constant(20, name='20')
c = tf.constant(30, name='30')

# 연산 정의하기
add_op = tf.add(a,b, name='add')
mul_op = tf.multiply(add_op, c, name='mul')

# 세션 시작하기
sess = tf.Session()
res = sess.run(mul_op)  # 식 평가하기
print(res)

# 텐서플로로 그래프 출력하기
tf.summary.FileWriter('.logs', sess.graph)

900


### 변수 사용하기

In [5]:
import tensorflow as tf

# 변수 정의하기
v = tf.Variable(0, name='v')

# 상수 정의하기
a = tf.constant(10, name='10')
b = tf.constant(20, name='20')

# 연산 정의하기
mul_op = tf.multiply(a, b, name='mul')
assign_op = tf.assign(v, mul_op)

# 세션 시작하기
sess = tf.Session()
# 연산 실행하기
sess.run(assign_op)

# 텐서플로로 그래프 출력하기
tf.summary.FileWriter('.logs', sess.graph)

#결과 출력하기
res = sess.run(v)
print(res)

200


### 플레이스홀더 사용하기

In [6]:
import tensorflow as tf

# 플레이스홀더 정의하기 
a = tf.placeholder(tf.int32, [5])

# 벡터를 2배 하는 연산 정의하기
two = tf.constant(2)
x2_op = a * two

# 세션 시작하기 
sess = tf.Session()

# 플레이스 홀더에 값을 넣어 실행하기 
res1 = sess.run(x2_op, feed_dict={ a: [1, 2, 3, 4, 5] })
print(res1)
res2 = sess.run(x2_op, feed_dict={ a: [5, 6, 7, 10, 100] })
print(res2)

[ 2  4  6  8 10]
[ 10  12  14  20 200]


In [7]:
import tensorflow as tf

# 플레이스홀더 정의하기 
a = tf.placeholder(tf.int32, [None, 2])

# 벡터를 2배 하는 연산 정의하기 
two = tf.constant(2)
x2_op = a * two

# 세션 시작하기 
sess = tf.Session()

# 플레이스 홀더에 값을 넣어 실행하기 
sample_list = [[1, 1], [2, 2], [3, 3], [4, 4]]
res = sess.run(x2_op, feed_dict={ a: sample_list })
print(res)

[[2 2]
 [4 4]
 [6 6]
 [8 8]]
